import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { hashPassword } from "../src/server/password";

const dbPath = path.join(process.cwd(), "dev.db");
const adapter = new PrismaLibSql({
  url: `file:${dbPath}`,
});
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seed başlıyor...");

  // ─── Demo Kullanıcılar ──────────────────────────────────
  const passwordHash = await hashPassword("123456");

  const adminUser = await prisma.user.upsert({
    where: { email: "admin@patiyuva.com" },
    update: {},
    create: {
      name: "Süper Admin",
      firstName: "Süper",
      lastName: "Admin",
      email: "admin@patiyuva.com",
      phone: "0555 000 00 00",
      passwordHash,
      role: "SUPER_ADMIN",
    },
  });

  const shelterAdmin = await prisma.user.upsert({
    where: { email: "barinak@patiyuva.com" },
    update: {},
    create: {
      name: "Barınak Yetkilisi",
      firstName: "Barınak",
      lastName: "Yetkilisi",
      email: "barinak@patiyuva.com",
      phone: "0555 111 11 11",
      passwordHash,
      role: "SHELTER_ADMIN",
    },
  });

  const normalUser = await prisma.user.upsert({
    where: { email: "kullanici@patiyuva.com" },
    update: {},
    create: {
      name: "Test Kullanıcı",
      firstName: "Test",
      lastName: "Kullanıcı",
      email: "kullanici@patiyuva.com",
      phone: "0555 222 22 22",
      passwordHash,
      role: "USER",
    },
  });

  console.log("Kullanıcılar oluşturuldu:", adminUser.email, shelterAdmin.email, normalUser.email);

  // ─── Barınaklar ─────────────────────────────────────────
  const sheltersData = [
    {
      id: "shelter-kadikoy",
      slug: "kadikoy-gecici-hayvan-bakimevi",
      name: "Kadıköy Belediyesi Geçici Hayvan Bakımevi",
      description: "Kadıköy Belediyesi Veteriner İşleri Müdürlüğü bünyesinde faaliyet gösteren geçici hayvan bakımevi; sahipsiz hayvanların bakımı, tedavisi ve sahiplendirilmesi çalışmalarını yürütmektedir.",
      city: "İstanbul",
      district: "Kadıköy",
      address: "Çamlık Mah. Parlak Sok., Ümraniye, İstanbul",
      phone: "0216 415 67 61",
      verified: true,
      verificationStatus: "VERIFIED",
      dataSourceType: "OFFICIAL",
      officialSourceUrl: "https://kadikoy.bel.tr/kurumsal/birimler/veteriner-isleri",
      services: JSON.stringify(["sahiplendirme", "veteriner"]),
      isDemo: false,
    },
    {
      id: "shelter-bornova",
      slug: "bornova-pako-sokak-hayvanlari-merkezi",
      name: "İzmir Pako Sokak Hayvanları Sosyal Yaşam Kampüsü",
      description: "İzmir Büyükşehir Belediyesi tarafından sokak hayvanları için kurulan Pako Sokak Hayvanları Sosyal Yaşam Kampüsü; modern yaşam alanları, klinik ve sahiplendirme birimleriyle hizmet vermektedir.",
      city: "İzmir",
      district: "Bornova",
      address: "Gökdere Mevkii, Bornova, İzmir",
      verified: true,
      verificationStatus: "VERIFIED",
      dataSourceType: "OFFICIAL",
      officialSourceUrl: "https://www.izmir.bel.tr",
      services: JSON.stringify(["sahiplendirme", "veteriner", "rehabilitasyon"]),
      isDemo: false,
    },
    {
      id: "shelter-sincan",
      slug: "sincan-gecici-hayvan-bakimevi",
      name: "ABB Sincan Geçici Hayvan Bakımevi ve Rehabilitasyon Merkezi",
      description: "Ankara Büyükşehir Belediyesi Sağlık İşleri Daire Başkanlığı bünyesindeki Sincan Geçici Hayvan Bakımevi ve Rehabilitasyon Merkezi; sahipsiz hayvanların toplanması, tedavisi ve sahiplendirilmesi hizmetlerini sunmaktadır.",
      city: "Ankara",
      district: "Sincan",
      address: "Ahi Evran Mah. 225. Cad. No:96-98, Sincan, Ankara",
      phone: "0 312 507 42 32",
      email: "sokakhayvanlari@ankara.bel.tr",
      verified: true,
      verificationStatus: "VERIFIED",
      dataSourceType: "OFFICIAL",
      officialSourceUrl: "https://www.ankara.bel.tr",
      services: JSON.stringify(["sahiplendirme", "veteriner", "rehabilitasyon"]),
      isDemo: false,
    },
    {
      id: "shelter-sahinbey",
      slug: "sahinbey-can-dostlari-barinagi",
      name: "Gaziantep Büyükşehir Belediyesi Hayvan Barınağı ve Rehabilitasyon Merkezi",
      description: "Gaziantep Büyükşehir Belediyesi tarafından işletilen hayvan barınağı ve rehabilitasyon merkezi; sokak hayvanlarının bakımını üstlenmekte ve ziyaret saatlerinde sahiplendirme çalışmalarını sürdürmektedir.",
      city: "Gaziantep",
      district: "Şahinbey",
      address: "Burç Yazıbağ Mah., Şahinbey, Gaziantep",
      workingHours: "Ziyaret saatleri: 14.00 - 16.00",
      verified: true,
      verificationStatus: "VERIFIED",
      dataSourceType: "OFFICIAL",
      officialSourceUrl: "https://www.gaziantep.bel.tr",
      services: JSON.stringify(["sahiplendirme", "veteriner"]),
      isDemo: false,
    },
    {
      id: "shelter-cankaya",
      slug: "cankaya-hayvan-barinagi",
      name: "Çankaya Hayvan Barınağı",
      description: "Örnek amaçlı hazırlanmış demo barınak profili. Bu kayıt gerçek bir kurumu temsil etmez.",
      city: "Ankara",
      district: "Çankaya",
      verified: false,
      verificationStatus: "UNVERIFIED",
      dataSourceType: "DEMO",
      services: JSON.stringify(["sahiplendirme"]),
      isDemo: true,
    },
    {
      id: "shelter-nilufer",
      slug: "nilufer-belediyesi-hayvan-bakimevi",
      name: "Nilüfer Belediyesi Hayvan Bakımevi",
      description: "Örnek amaçlı hazırlanmış demo bakımevi profili. Bu kayıt gerçek bir kurumu temsil etmez.",
      city: "Bursa",
      district: "Nilüfer",
      verified: false,
      verificationStatus: "UNVERIFIED",
      dataSourceType: "DEMO",
      services: JSON.stringify(["sahiplendirme"]),
      isDemo: true,
    },
    {
      id: "shelter-kepez",
      slug: "kepez-sahipsiz-hayvan-bakimevi",
      name: "Kepez Sahipsiz Hayvan Bakımevi",
      description: "Örnek amaçlı hazırlanmış demo bakımevi profili. Bu kayıt gerçek bir kurumu temsil etmez.",
      city: "Antalya",
      district: "Kepez",
      verified: false,
      verificationStatus: "UNVERIFIED",
      dataSourceType: "DEMO",
      services: JSON.stringify(["sahiplendirme"]),
      isDemo: true,
    },
    {
      id: "shelter-tepebasi",
      slug: "tepebasi-dogal-yasam-merkezi",
      name: "Tepebaşı Doğal Yaşam Merkezi",
      description: "Örnek amaçlı hazırlanmış demo yaşam merkezi profili. Bu kayıt gerçek bir kurumu temsil etmez.",
      city: "Eskişehir",
      district: "Tepebaşı",
      verified: false,
      verificationStatus: "UNVERIFIED",
      dataSourceType: "DEMO",
      services: JSON.stringify(["sahiplendirme"]),
      isDemo: true,
    },
  ];

  for (const shelter of sheltersData) {
    await prisma.shelter.upsert({
      where: { id: shelter.id },
      update: shelter,
      create: shelter,
    });
  }

  console.log("Barınaklar oluşturuldu:", sheltersData.length);

  // Barınak admin ataması
  const kadikoyShelter = await prisma.shelter.findUnique({ where: { id: "shelter-kadikoy" } });
  if (kadikoyShelter) {
    await prisma.shelterAdmin.upsert({
      where: { userId_shelterId: { userId: shelterAdmin.id, shelterId: kadikoyShelter.id } },
      update: {},
      create: { userId: shelterAdmin.id, shelterId: kadikoyShelter.id },
    });
  }

  // ─── Hayvanlar ──────────────────────────────────────────
  const animalsData = [
    {
      id: "animal-boncuk",
      slug: "boncuk",
      name: "Boncuk",
      species: "Köpek",
      breed: "Melez",
      age: "2 yaş",
      ageGroup: "Genç",
      size: "Orta",
      gender: "Dişi",
      city: "İstanbul",
      district: "Kadıköy",
      shelterId: "shelter-kadikoy",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Orta",
      character: "Sakin, insanlarla çabuk bağ kuran ve yürüyüşleri seven bir dost.",
      description: "Boncuk apartman yaşamına uyum sağlayabilecek, temel komutları bilen ve düzenli yürüyüşle mutlu olan sevgi dolu bir köpek.",
      healthDescription: "Barınağa gelişinde genel sağlık taramasından geçmiştir.",
      traits: JSON.stringify(["Sakin", "İnsanlarla Uyumlu", "Çocuklarla Uyumlu"]),
      goodWithChildren: 1,
      goodWithDogs: null,
      goodWithCats: null,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: 1,
      microchipped: 1,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: false,
    },
    {
      id: "animal-minnos",
      slug: "minnos",
      name: "Minnoş",
      species: "Kedi",
      breed: "Tekir",
      age: "8 ay",
      ageGroup: "Yavru",
      size: "Küçük",
      gender: "Dişi",
      city: "Ankara",
      district: "Çankaya",
      shelterId: "shelter-cankaya",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Yüksek",
      character: "Meraklı, oyuncu ve kucakta uyumayı seven sosyal bir kedi.",
      description: "Minnoş yeni insanlara kısa sürede alışır. Oyuncaklarla vakit geçirmeyi ve sakin ev ortamlarını çok sever.",
      traits: JSON.stringify(["Oyuncu", "İnsanlarla Uyumlu"]),
      goodWithChildren: null,
      goodWithDogs: null,
      goodWithCats: 1,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: null,
      microchipped: 0,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
    {
      id: "animal-karamel",
      slug: "karamel",
      name: "Karamel",
      species: "Köpek",
      breed: "Melez",
      age: "4 yaş",
      ageGroup: "Yetişkin",
      size: "Büyük",
      gender: "Erkek",
      city: "İzmir",
      district: "Bornova",
      shelterId: "shelter-bornova",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Yüksek",
      character: "Enerjik, sadık ve bahçeli evlerde daha rahat edebilecek bir dost.",
      description: "Karamel hareketli ailelere uygundur. Koşmayı, oyun oynamayı ve insanlarla temas kurmayı sever.",
      traits: JSON.stringify(["Enerjik", "Diğer Hayvanlarla Uyumlu"]),
      goodWithChildren: null,
      goodWithDogs: 1,
      goodWithCats: null,
      homeSuitable: 0,
      gardenRequired: 1,
      vaccinated: 1,
      neutered: 1,
      microchipped: 1,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: false,
    },
    {
      id: "animal-zeytin",
      slug: "zeytin",
      name: "Zeytin",
      species: "Kedi",
      breed: "Tekir",
      age: "3 yaş",
      ageGroup: "Yetişkin",
      size: "Orta",
      gender: "Erkek",
      city: "Bursa",
      district: "Nilüfer",
      shelterId: "shelter-nilufer",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Düşük",
      character: "Sessiz, gözlemci ve sakin bir ev düzeninde huzurlu olur.",
      description: "Zeytin ilk tanışmada çekingen davranabilir, güven kurduğunda sahibinin yanından ayrılmayan nazik bir arkadaş olur.",
      traits: JSON.stringify(["Sakin", "Ev Yaşamına Uygun"]),
      goodWithChildren: null,
      goodWithDogs: null,
      goodWithCats: null,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: null,
      microchipped: null,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
    {
      id: "animal-luna",
      slug: "luna",
      name: "Luna",
      species: "Köpek",
      breed: "Melez",
      age: "6 yaş",
      ageGroup: "Yetişkin",
      size: "Küçük",
      gender: "Dişi",
      city: "Antalya",
      district: "Kepez",
      shelterId: "shelter-kepez",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Orta",
      character: "Uysal, çocuklarla uyumlu ve evde sakin kalmayı bilen bir karakter.",
      description: "Luna dengeli mizacı sayesinde ilk kez köpek sahiplenecek aileler için de güzel bir adaydır.",
      traits: JSON.stringify(["Sakin", "Çocuklarla Uyumlu", "Ev Yaşamına Uygun"]),
      goodWithChildren: 1,
      goodWithDogs: null,
      goodWithCats: null,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: 1,
      microchipped: null,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
    {
      id: "animal-pati",
      slug: "pati",
      name: "Pati",
      species: "Kedi",
      breed: "Sarman",
      age: "10 yaş",
      ageGroup: "Yaşlı",
      size: "Orta",
      gender: "Erkek",
      city: "Eskişehir",
      district: "Tepebaşı",
      shelterId: "shelter-tepebasi",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Düşük",
      character: "Sevecen, sakin ve günün büyük kısmını sıcak bir köşede geçirmeyi sever.",
      description: "Pati yaşlı ama çok sevgi dolu bir kedidir. Ona sessiz, güvenli ve düzenli bir yuva iyi gelir.",
      traits: JSON.stringify(["Sakin", "Ev Yaşamına Uygun"]),
      goodWithChildren: null,
      goodWithDogs: null,
      goodWithCats: 1,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: null,
      microchipped: null,
      healthChecked: null,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
    {
      id: "animal-findik",
      slug: "findik",
      name: "Fındık",
      species: "Kedi",
      breed: "Melez",
      age: "5 ay",
      ageGroup: "Yavru",
      size: "Küçük",
      gender: "Dişi",
      city: "İstanbul",
      district: "Kadıköy",
      shelterId: "shelter-kadikoy",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Yüksek",
      character: "Enerjik, meraklı ve oyun saatlerini çok seven küçük bir kedi.",
      description: "Fındık yavru olduğu için keşfetmeye ve oynamaya bayılır.",
      traits: JSON.stringify(["Oyuncu", "Enerjik"]),
      goodWithChildren: null,
      goodWithDogs: null,
      goodWithCats: 1,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: null,
      microchipped: null,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: false,
    },
    {
      id: "animal-duman",
      slug: "duman",
      name: "Duman",
      species: "Köpek",
      breed: "Melez",
      age: "3 yaş",
      ageGroup: "Yetişkin",
      size: "Büyük",
      gender: "Erkek",
      city: "Gaziantep",
      district: "Şahinbey",
      shelterId: "shelter-sahinbey",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Yüksek",
      character: "Güçlü, sadık ve insanlarla güçlü bağ kuran bir köpek.",
      description: "Duman aktif bir yaşamı olan, ona güven verebilecek sahipler arıyor.",
      traits: JSON.stringify(["Enerjik", "İnsanlarla Uyumlu"]),
      goodWithChildren: null,
      goodWithDogs: 1,
      goodWithCats: null,
      homeSuitable: 0,
      gardenRequired: 1,
      vaccinated: 1,
      neutered: 1,
      microchipped: null,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: false,
    },
    {
      id: "animal-sila",
      slug: "sila",
      name: "Şila",
      species: "Köpek",
      breed: "Melez",
      age: "1 yaş",
      ageGroup: "Genç",
      size: "Orta",
      gender: "Dişi",
      city: "Antalya",
      district: "Kepez",
      shelterId: "shelter-kepez",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "PENDING",
      energyLevel: "Yüksek",
      character: "Canlı, oyuncu ve çocuklarla çok iyi anlaşan bir karakter.",
      description: "Şila ile ilgili bir sahiplenme süreci devam etmektedir.",
      traits: JSON.stringify(["Oyuncu", "Çocuklarla Uyumlu", "İnsanlarla Uyumlu"]),
      goodWithChildren: 1,
      goodWithDogs: null,
      goodWithCats: null,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: 1,
      neutered: null,
      microchipped: null,
      healthChecked: 1,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1560807707-8cc77767d783?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
    {
      id: "animal-pamuk",
      slug: "pamuk",
      name: "Pamuk",
      species: "Diğer",
      breed: "Tavşan",
      age: "1 yaş",
      ageGroup: "Genç",
      size: "Küçük",
      gender: "Dişi",
      city: "İzmir",
      district: "Bornova",
      shelterId: "shelter-bornova",
      sourceType: "SHELTER",
      dataSourceType: "DEMO",
      adoptionStatus: "AVAILABLE",
      energyLevel: "Düşük",
      character: "Sakin, sessiz ve düzenli bir yaşam alanında mutlu olan bir tavşan.",
      description: "Pamuk gürültüden uzak, sakin bir ortamda huzurla yaşayabilir.",
      traits: JSON.stringify(["Sakin", "Ev Yaşamına Uygun"]),
      goodWithChildren: null,
      goodWithDogs: null,
      goodWithCats: null,
      homeSuitable: 1,
      gardenRequired: 0,
      vaccinated: null,
      neutered: null,
      microchipped: null,
      healthChecked: null,
      imageUrls: JSON.stringify([
        "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=1200&q=80",
      ]),
      isDemo: true,
    },
  ];

  for (const animal of animalsData) {
    await prisma.animal.upsert({
      where: { id: animal.id },
      update: animal,
      create: animal,
    });
  }

  console.log("Hayvanlar oluşturuldu:", animalsData.length);

  // ─── Demo Başvuru ───────────────────────────────────────
  await prisma.adoptionApplication.create({
    data: {
      animalId: "animal-boncuk",
      userId: normalUser.id,
      shelterId: "shelter-kadikoy",
      userName: normalUser.name,
      userEmail: normalUser.email,
      phone: "0555 222 22 22",
      city: "İstanbul",
      houseType: "Apartman dairesi",
      hasGarden: false,
      previousExperience: true,
      hasOtherPets: false,
      reason: "Sevgi dolu bir yuva açmak istiyorum",
      availableTime: "Her gün sabah ve akşam",
      status: "PENDING",
    },
  });

  console.log("Demo başvuru oluşturuldu");
  console.log("Seed tamamlandı!");
}

main()
  .catch((e) => {
    console.error("Seed hatası:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
